version: '3.8'

services:
  db:
    image: postgres:16
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: lotsoflovecindy
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  app:
    build:
      context: ./backend
    container_name: my-go-app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: lotsoflovecindy
      GOOGLE_APPLICATION_CREDENTIALS: /app/credentials.json
    volumes:
      - /Users/cindycheung/Documents/Software/lotsoflovecindy/credentials.json:/app/credentials.json

volumes:
  pgdata:
