version: 2

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - gocritic
  disable:
    - revive

linters-settings:
  revive:
    config: .revive.toml
    disable:
      - package-comments
  errcheck:
    exclude:
      - io.Closer.Close
      - net/http.ResponseWriter.Write

issues:
  exclude-rules:
    - linters:
        - revive
      text: "package-comments"
